apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: app-html
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-html
  template:
    metadata:
      labels:
        app: app-html
        editor: vscode
    spec:
      containers:
      - name: app-html
        image: mauroslucios/app-kubernetes-html:v1.3
        ports:
          - containerPort: 80
