[cluster_docker_swarm]
3.85.231.191 ansible_ssh_private_key_file=/home/mauros/Documentos/dio/iac/mauroslucios.pem
54.87.183.216 ansible_ssh_private_key_file=/home/mauros/Documentos/dio/iac/mauroslucios.pem
3.83.68.2 ansible_ssh_private_key_file=/home/mauros/Documentos/dio/iac/mauroslucios.pem